---
- name: Install python application and run with supervisord
  become: true
  become_method: sudo

  vars:
    app_location: /webapps/devops
    app_repo: https://bitbucket.org/azneita/devops-challenge.git
    nginx_proxy: localhost:5000
    app_name: myapp
   
  roles:
    - timezone
    - nginx
    - application
    - supervisor


