---
- name: Playbook
  hosts: all
  become: true
  become_method: sudo

  vars:
    app_location: /webapps/devops
    app_repo: https://bitbucket.org/azneita/devops-challenge.git
    nginx_proxy: localhost:5000
    app_name: myapp
   
  roles:
    - os_hardening
    - { role: timezone, when: ansible_os_family == 'Debian' or ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' }
#    - nginx
#    - application
#    - supervisor


