apiVersion: v1
kind: Service
metadata:
    name: {{ app }}-svc
    labels:
        app: {{ app }}
spec:
    type: ClusterIP
    ports:
    - port: {{ containerPort }}
      nodePort: {{ nodeport }}
      protocol: {{ nodeprotocol }}
    selector:
        app: {{ app }}