---
### Nginx Installation and Configuration
# file: roles/nginx/tasks/main.yml
- name: Add Nginx Repository
  apt_repository:
    repo: 'ppa:nginx/stable'
    state: present
  register: nginx_repo_install

- name: Install Nginx
  apt:
    pkg: nginx
    state: present
    update_cache: true
  when: nginx_repo_install is success
  register: nginx_installed
  notify:
    - restart_nginx

- name: Add proxy site Configuration
  when: nginx_installed is success
  template:
    src: nginx_config
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
  register: add_proxysite

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  when: add_proxysite is success

