FROM centos:latest

RUN yum install epel-release yum-utils -y && \
    yum install httpd -y && \
    yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y && \
    yum-config-manager --enable remi-php56 && \
    yum install php php-mcrypt php-cli php-gd php-curl php-mysql php-zip -y

ADD https://wordpress.org/latest.tar.gz /tmp
RUN cd /tmp/ && tar -zxvf latest.tar.gz && cp -rf /tmp/wordpress/* /var/www/html/
RUN chown -R apache:root /var/www/html

EXPOSE 80
CMD ["-D", "FOREGROUND"]
ENTRYPOINT ["/usr/sbin/httpd"]
